# Sequences VOILA

In [1]:
import time
from collections import abc #abc AbstractBaseClass 

issubclass(list, abc.Sequence)  #list , bytearray, array.array, collections.deque are mutable sequences

True

In [92]:
issubclass(tuple, abc.MutableSequence)  #immutable sequences tuple str bytes

False

# LIST COMPREHENSION - LISTCOMP  [ ] 
## GREEDY EXECUTION 


In [93]:
symbols: str = '!@#$%'
codes: list[int] = [ord(s) for s in symbols]  # list comprehension pythonic way of doing things for readability 
codes

[33, 64, 35, 36, 37]

In [94]:
# listcomp in the use of cartesian products
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

shirts = [(c, s) for c in colors  #inside [] () {} line breaks are ignored 
          for s in sizes]  # it will loop the sizes for every color 
shirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

# GENERATOR EXPRESSIONS - GENEXP ()
## ONE AT A TIME PROCESSING INSTEAD OF ALL AT ONCE

In [95]:
 # use genexp to make them one by one instead of all at once
symbols: str  = '!@#$%'
codes = (ord(s) for s in symbols)  # codes is a genexp now you can use to retrieve indivudal items 
print(codes)
print(tuple(codes))
#now are codes are empty
print(tuple(codes))

<generator object <genexpr> at 0x15226f1b0>
(33, 64, 35, 36, 37)
()


In [96]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in (f'---{c},{s}---' for c in colors for s in sizes):  #formating string is genexp
    print(tshirt)

colors = (c for c in colors)
print(colors)  # genexp, if we print them out them are gone
for c in colors:
    print(c)
    break  # break so we have one color left
print(tuple(colors))  # print it out showing we only have one
print(tuple(colors))  # now nothing


---black,S---
---black,M---
---black,L---
---white,S---
---white,M---
---white,L---
<generator object <genexpr> at 0x15226f530>
black
('white',)
()


In [97]:
#more on tuples 
city, year = ('Tokyo', 2024)  #unpqck into variables
traveler_ids = [('USA', 1234), ('FRA', 5678)]
for _id in sorted(traveler_ids):
    print("%s/%s" % _id)  # the % will unpack into the %s's
for country, _ in traveler_ids:  # use _ as a dummy variable
    print(country)

FRA/5678
USA/1234
USA
FRA


In [98]:
x, y, *z = range(0, 10)  #unpack the rest into z
print(x, y, z)

0 1 [2, 3, 4, 5, 6, 7, 8, 9]


In [99]:
x, *y, z = range(0, 10)  #unpack the ends into x and z the rest in y
print(x, y, z)

0 [1, 2, 3, 4, 5, 6, 7, 8] 9


In [100]:
#unpacking in funciton calls and definitions

def fun(a, b, c, d, *rest):
    return a, b, c, d, rest  #if i return *rest it would unpack the tupled packed rest


fun(*[1, 2], *range(10))  #xpand all params


(1, 2, 0, 1, (2, 3, 4, 5, 6, 7, 8, 9))

## Pattern matching with sequences using match and case

In [101]:
match tuple(input('Enter a number: ')):
    case ['1',*rest]:
        print("you entered a 1 and ",rest)
    case [*first,'2',]:
        print(first,"2")

you entered a 1 and  ['8', '0', '1', '6', '5', '1', '1', '9', '4', '7']


## Named slices then applying them 

In [102]:
# you can do name slices and then apply them
items = """
this is the first description        item 1
a really cool item                  item 2
not as cool                         item 3
"""
DESCRIPTION = slice(0,35)
ITEM = slice(35,43)
lines = items.split('\n')[1:]
for item in lines:
    print(item[DESCRIPTION],item[ITEM]) # use the slice here to pull out only that column range

this is the first description         item 1
a really cool item                   item 2
not as cool                          item 3
 


## Using * to repeat lists, and lists of lists, and lists of lists of ... :) 

In [103]:
# you can use * to repeat lists 
l = [1,2,3,[4,5]]
l*3 # repeat itself 3 times 

[1, 2, 3, [4, 5], 1, 2, 3, [4, 5], 1, 2, 3, [4, 5]]

In [104]:
'abc'*10

'abcabcabcabcabcabcabcabcabcabc'

In [105]:
#let's make a tic tac toe board using * on lists
board = [[' '] * 3 for _ in range (3)]
    

In [106]:
board

[[' ', ' ', ' '], [' ', ' ', ' '], [' ', ' ', ' ']]

In [107]:
board[1][1]='X'

In [108]:
board

[[' ', ' ', ' '], [' ', 'X', ' '], [' ', ' ', ' ']]

In [109]:
#tempting to do this
board = [[' ']*3]* 3


In [110]:
board[0][0]='X' # but as you see it references the same list 3 times so it's not what you would probably want
board

[['X', ' ', ' '], ['X', ' ', ' '], ['X', ' ', ' ']]

## Augmented assignment with sequences using += and *=

In [111]:
#augmented assignment with sequences += and *=
#these correspond to magic methods __iadd__ in place addition fall back is __add__
list1 = [1,2,3]
id(list1)

4393357120

In [112]:
list1 *= 3 #in place
print(list1)
id(list1) # it references the same object/same id

[1, 2, 3, 1, 2, 3, 1, 2, 3]


4393357120

In [113]:
#for tuples a new object is created
tuple1 = (1,2,3)    
print(id(tuple1))
tuple1 *= 3 
id(tuple1) # these wont' match because the in place editing created a new object since tuples are immutable 

4393095104


4388737248

## A Riddle about modifying tuples/lists with +=

In [114]:
t = (1,2,[3,4])
t[2]+=[5,6]

TypeError: 'tuple' object does not support item assignment

In [115]:
t

(1, 2, [3, 4, 5, 6])

## It added it to the list, but also generated an error?!

In [116]:
from array import array
from random import random
floats = array('d',[random() for _ in range(10**7)]) # d stands for double precision float, from generator expression for _ in range(10**7)

In [117]:
floats[-1]


0.530369349065671

## sort vs sorted and using the key to sort by differnt thigns

In [118]:
fruits : list[str] = ['orange','apple','rasberry','z']
fruits.sort(key=lambda l_x: len(l_x)) #sort the fruits array in place by the len
fruits

['z', 'apple', 'orange', 'rasberry']

In [119]:
new_fruits = sorted(fruits) #returns a sorted list, using default sort key of alphaetical
new_fruits

['apple', 'orange', 'rasberry', 'z']

## arrays are the fastest and most efficient way to store (read and write) numeric values in python

In [120]:
from array import array
from random import random
import time

floats = array('d',[random() for _ in range(10**7)])
print(floats[-1])
with  open('floats.bin', 'wb') as fp: 
    tick= time.process_time()
    floats.tofile(fp)
    print(f"{time.process_time()-tick:*^30.4f}")

floats2 = array('d')

with open('floats.bin', 'rb') as fp:
    tick = time.process_time()
    floats2.fromfile(fp,10**7) # read a million doubles 
    print(f"{time.process_time()-tick:*^30.4f}")
print(floats2[-1])   
print(floats==floats2)

0.2753633391396424
************0.0191************
************0.0219************
0.2753633391396424
True


## memoryview handle slices of arrays without copying bytes
let's you change their shape using cast and modify elements 

In [121]:
from array import array
octets = array('B',range(6))
m1 = memoryview(octets)
m2 = m1.cast('B',(3,2))


In [122]:
print(m2.tolist())
m2[1,1] = 33
octets

[[0, 1], [2, 3], [4, 5]]


array('B', [0, 1, 2, 33, 4, 5])

## numpy is the go to for all array and matrix processing 

In [160]:
import numpy as np

np_array = np.arange(12)
print(np_array,np_array.shape)
np_array.shape = 3,4 # reshape 
print(np_array)
print(f' first row {np_array[0,:]} \n second row {np_array[1,:]}')
print(f' third row {np_array[2:,]}')
print(np_array.transpose()) # transpose rose becomes columns and 

np_array*=10 # scalar multiply entire matrix
print('before save', np_array)
np.save('np_array.npy',np_array)
np_array2 = np.load('np_array.npy')
print('after load', np_array2)
# columns become rows 



[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 first row [0 1 2 3] 
 second row [4 5 6 7]
 third row [[ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
before save [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
after load [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


# deque for inserting and removing from both ends of a list in an efficient way

In [181]:
from collections import deque
dq = deque(range(10),maxlen=10) # bound it so we keep the last 10 items only 
print(dq)
dq.rotate(3);print(dq) # rotate will move from the back to the front or vice versa automatically 
dq.rotate(-3);print(dq) # this will rortate teh other direction 
dq.appendleft(0);print(dq) # will append and push any out the other side
dq.append(0);print(dq) # same but at the end 
dq.extend([-1,-1,-1]);print(dq) # basically this acts as appending multiple elements and pushing any out the other side
dq.extendleft([-1,-1,-1]);print(dq) # same thinb but for the left side
num = dq.popleft();print(dq);print(num)
num = dq.pop();print(dq);print(num)


deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([0, 0, 1, 2, 3, 4, 5, 6, 7, 8], maxlen=10)
deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 0], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 0, -1, -1, -1], maxlen=10)
deque([-1, -1, -1, 3, 4, 5, 6, 7, 8, 0], maxlen=10)
deque([-1, -1, 3, 4, 5, 6, 7, 8, 0], maxlen=10)
-1
deque([-1, -1, 3, 4, 5, 6, 7, 8], maxlen=10)
0
